import { createContext, useContext, useState } from 'react';

const AppContext = createContext(null);

const mockJobs = [
    {
        "id": 1,
        "title": "Financial Analyst",
        "company": "Razorpay",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b915\u201320 LPA",
        "platform": "Naukri",
        "posted": "6 days ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "RP",
        "description": "Exciting opportunity for a Financial Analyst at Razorpay. Must have experience in Excel, Financial Modeling, SQL. Join our dynamic team in Bangalore.",
        "matchScore": 68,
        "remote": false,
        "companySize": "Startup",
        "industry": "Finance"
    },
    {
        "id": 2,
        "title": "Data Scientist",
        "company": "Reliance Industries",
        "location": "Mumbai, MH",
        "type": "Contract",
        "salary": "\u20b914\u201324 LPA",
        "platform": "Indeed",
        "posted": "4 weeks ago",
        "experience": "2+ years",
        "saved": true,
        "logo": "RI",
        "description": "Exciting opportunity for a Data Scientist at Reliance Industries. Must have experience in Python, TensorFlow, PyTorch. Join our dynamic team in Mumbai.",
        "matchScore": 79,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Tech"
    },
    {
        "id": 3,
        "title": "Content Strategist",
        "company": "Razorpay",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b916\u201321 LPA",
        "platform": "IIM Jobs",
        "posted": "1 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "RP",
        "description": "Exciting opportunity for a Content Strategist at Razorpay. Must have experience in Copywriting, SEO, Social Media. Join our dynamic team in Bangalore.",
        "matchScore": 85,
        "remote": false,
        "companySize": "Startup",
        "industry": "Marketing"
    },
    {
        "id": 4,
        "title": "Digital Marketing Manager",
        "company": "Delhivery",
        "location": "Gurgaon, HR",
        "type": "Contract",
        "salary": "\u20b934\u201344 LPA",
        "platform": "LinkedIn",
        "posted": "3 weeks ago",
        "experience": "9+ years",
        "saved": false,
        "logo": "DL",
        "description": "Exciting opportunity for a Digital Marketing Manager at Delhivery. Must have experience in SEO, SEM, Google Ads. Join our dynamic team in Gurgaon.",
        "matchScore": 81,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Marketing"
    },
    {
        "id": 5,
        "title": "Content Strategist",
        "company": "Swiggy",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b99\u201321 LPA",
        "platform": "Indeed",
        "posted": "4 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "SW",
        "description": "Exciting opportunity for a Content Strategist at Swiggy. Must have experience in Copywriting, SEO, Social Media. Join our dynamic team in Bangalore.",
        "matchScore": 86,
        "remote": true,
        "companySize": "Mid-sized",
        "industry": "Marketing"
    },
    {
        "id": 6,
        "title": "Digital Marketing Manager",
        "company": "HDFC Bank",
        "location": "Mumbai, MH",
        "type": "Full-time",
        "salary": "\u20b936\u201354 LPA",
        "platform": "Instahyre",
        "posted": "3 weeks ago",
        "experience": "8+ years",
        "saved": false,
        "logo": "HB",
        "description": "Exciting opportunity for a Digital Marketing Manager at HDFC Bank. Must have experience in SEO, SEM, Google Ads. Join our dynamic team in Mumbai.",
        "matchScore": 69,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Marketing"
    },
    {
        "id": 7,
        "title": "Supply Chain Analyst",
        "company": "Zoho",
        "location": "Chennai, TN",
        "type": "Full-time",
        "salary": "\u20b911\u201321 LPA",
        "platform": "Naukri",
        "posted": "4 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "ZH",
        "description": "Exciting opportunity for a Supply Chain Analyst at Zoho. Must have experience in Inventory Management, SQL. Join our dynamic team in Chennai.",
        "matchScore": 84,
        "remote": false,
        "companySize": "Large",
        "industry": "Operations"
    },
    {
        "id": 8,
        "title": "Investment Banker",
        "company": "ICICI Bank",
        "location": "Mumbai, MH",
        "type": "Full-time",
        "salary": "\u20b915\u201322 LPA",
        "platform": "Instahyre",
        "posted": "1 weeks ago",
        "experience": "1+ years",
        "saved": true,
        "logo": "IB",
        "description": "Exciting opportunity for a Investment Banker at ICICI Bank. Must have experience in Valuation, M&A, Pitch Decks. Join our dynamic team in Mumbai.",
        "matchScore": 74,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Finance"
    },
    {
        "id": 9,
        "title": "Operations Manager",
        "company": "Paytm",
        "location": "Noida, UP",
        "type": "Remote",
        "salary": "\u20b940\u201358 LPA",
        "platform": "Indeed",
        "posted": "1 weeks ago",
        "experience": "9+ years",
        "saved": true,
        "logo": "PT",
        "description": "Exciting opportunity for a Operations Manager at Paytm. Must have experience in Supply Chain, Logistics, SAP. Join our dynamic team in Noida.",
        "matchScore": 81,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Operations"
    },
    {
        "id": 10,
        "title": "Growth Hacker",
        "company": "Tech Mahindra",
        "location": "Pune, MH",
        "type": "Full-time",
        "salary": "\u20b99\u201319 LPA",
        "platform": "Naukri",
        "posted": "3 weeks ago",
        "experience": "4+ years",
        "saved": false,
        "logo": "TM",
        "description": "Exciting opportunity for a Growth Hacker at Tech Mahindra. Must have experience in A/B Testing, User Acquisition. Join our dynamic team in Pune.",
        "matchScore": 97,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Marketing"
    },
    {
        "id": 11,
        "title": "Talent Acquisition Specialist",
        "company": "Delhivery",
        "location": "Gurgaon, HR",
        "type": "Contract",
        "salary": "\u20b917\u201323 LPA",
        "platform": "Naukri",
        "posted": "2 weeks ago",
        "experience": "3+ years",
        "saved": true,
        "logo": "DL",
        "description": "Exciting opportunity for a Talent Acquisition Specialist at Delhivery. Must have experience in Sourcing, Screening, LinkedIn. Join our dynamic team in Gurgaon.",
        "matchScore": 79,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Operations"
    },
    {
        "id": 12,
        "title": "Supply Chain Analyst",
        "company": "ICICI Bank",
        "location": "Mumbai, MH",
        "type": "Contract",
        "salary": "\u20b915\u201322 LPA",
        "platform": "LinkedIn",
        "posted": "7 days ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "IB",
        "description": "Exciting opportunity for a Supply Chain Analyst at ICICI Bank. Must have experience in Inventory Management, SQL. Join our dynamic team in Mumbai.",
        "matchScore": 75,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Operations"
    },
    {
        "id": 13,
        "title": "Risk Manager",
        "company": "Infosys",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b937\u201351 LPA",
        "platform": "Instahyre",
        "posted": "2 weeks ago",
        "experience": "9+ years",
        "saved": false,
        "logo": "IN",
        "description": "Exciting opportunity for a Risk Manager at Infosys. Must have experience in Risk Analysis, Compliance, SAS. Join our dynamic team in Bangalore.",
        "matchScore": 84,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Finance"
    },
    {
        "id": 14,
        "title": "Full Stack Developer",
        "company": "Razorpay",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b911\u201316 LPA",
        "platform": "Naukri",
        "posted": "4 days ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "RP",
        "description": "Exciting opportunity for a Full Stack Developer at Razorpay. Must have experience in MERN Stack, AWS. Join our dynamic team in Bangalore.",
        "matchScore": 90,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 15,
        "title": "Content Strategist",
        "company": "Freshworks",
        "location": "Chennai, TN",
        "type": "Remote",
        "salary": "\u20b913\u201325 LPA",
        "platform": "Naukri",
        "posted": "3 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "FW",
        "description": "Exciting opportunity for a Content Strategist at Freshworks. Must have experience in Copywriting, SEO, Social Media. Join our dynamic team in Chennai.",
        "matchScore": 84,
        "remote": false,
        "companySize": "Large",
        "industry": "Marketing"
    },
    {
        "id": 16,
        "title": "iOS Developer",
        "company": "Razorpay",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b916\u201321 LPA",
        "platform": "Instahyre",
        "posted": "6 days ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "RP",
        "description": "Exciting opportunity for a iOS Developer at Razorpay. Must have experience in Swift, SwiftUI. Join our dynamic team in Bangalore.",
        "matchScore": 68,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 17,
        "title": "UI/UX Designer",
        "company": "Swiggy",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b99\u201318 LPA",
        "platform": "LinkedIn",
        "posted": "5 days ago",
        "experience": "3+ years",
        "saved": false,
        "logo": "SW",
        "description": "Exciting opportunity for a UI/UX Designer at Swiggy. Must have experience in Figma, Adobe XD, Prototyping. Join our dynamic team in Bangalore.",
        "matchScore": 97,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Tech"
    },
    {
        "id": 18,
        "title": "Talent Acquisition Specialist",
        "company": "CRED",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b917\u201329 LPA",
        "platform": "Glassdoor",
        "posted": "2 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "CR",
        "description": "Exciting opportunity for a Talent Acquisition Specialist at CRED. Must have experience in Sourcing, Screening, LinkedIn. Join our dynamic team in Bangalore.",
        "matchScore": 86,
        "remote": false,
        "companySize": "Startup",
        "industry": "Operations"
    },
    {
        "id": 19,
        "title": "Talent Acquisition Specialist",
        "company": "Swiggy",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b99\u201317 LPA",
        "platform": "Instahyre",
        "posted": "2 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "SW",
        "description": "Exciting opportunity for a Talent Acquisition Specialist at Swiggy. Must have experience in Sourcing, Screening, LinkedIn. Join our dynamic team in Bangalore.",
        "matchScore": 67,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Operations"
    },
    {
        "id": 20,
        "title": "Financial Analyst",
        "company": "TCS",
        "location": "Mumbai, MH",
        "type": "Full-time",
        "salary": "\u20b914\u201322 LPA",
        "platform": "Instahyre",
        "posted": "4 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "TC",
        "description": "Exciting opportunity for a Financial Analyst at TCS. Must have experience in Excel, Financial Modeling, SQL. Join our dynamic team in Mumbai.",
        "matchScore": 97,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Finance"
    },
    {
        "id": 21,
        "title": "Financial Analyst",
        "company": "Zerodha",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b914\u201322 LPA",
        "platform": "Glassdoor",
        "posted": "3 weeks ago",
        "experience": "3+ years",
        "saved": false,
        "logo": "ZD",
        "description": "Exciting opportunity for a Financial Analyst at Zerodha. Must have experience in Excel, Financial Modeling, SQL. Join our dynamic team in Bangalore.",
        "matchScore": 94,
        "remote": false,
        "companySize": "Startup",
        "industry": "Finance"
    },
    {
        "id": 22,
        "title": "Senior Frontend Developer",
        "company": "Zerodha",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b928\u201338 LPA",
        "platform": "IIM Jobs",
        "posted": "3 weeks ago",
        "experience": "9+ years",
        "saved": false,
        "logo": "ZD",
        "description": "Exciting opportunity for a Senior Frontend Developer at Zerodha. Must have experience in React, TypeScript, Next.js. Join our dynamic team in Bangalore.",
        "matchScore": 76,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 23,
        "title": "Financial Analyst",
        "company": "Infosys",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b911\u201317 LPA",
        "platform": "Instahyre",
        "posted": "3 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "IN",
        "description": "Exciting opportunity for a Financial Analyst at Infosys. Must have experience in Excel, Financial Modeling, SQL. Join our dynamic team in Bangalore.",
        "matchScore": 61,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Finance"
    },
    {
        "id": 24,
        "title": "Growth Hacker",
        "company": "Urban Company",
        "location": "Gurgaon, HR",
        "type": "Full-time",
        "salary": "\u20b99\u201318 LPA",
        "platform": "Glassdoor",
        "posted": "4 weeks ago",
        "experience": "4+ years",
        "saved": true,
        "logo": "UC",
        "description": "Exciting opportunity for a Growth Hacker at Urban Company. Must have experience in A/B Testing, User Acquisition. Join our dynamic team in Gurgaon.",
        "matchScore": 84,
        "remote": false,
        "companySize": "Startup",
        "industry": "Marketing"
    },
    {
        "id": 25,
        "title": "Chartered Accountant",
        "company": "Nykaa",
        "location": "Mumbai, MH",
        "type": "Remote",
        "salary": "\u20b99\u201318 LPA",
        "platform": "Glassdoor",
        "posted": "1 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "NK",
        "description": "Exciting opportunity for a Chartered Accountant at Nykaa. Must have experience in Taxation, Auditing, GST. Join our dynamic team in Mumbai.",
        "matchScore": 62,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Finance"
    },
    {
        "id": 26,
        "title": "Digital Marketing Manager",
        "company": "TCS",
        "location": "Mumbai, MH",
        "type": "Full-time",
        "salary": "\u20b936\u201346 LPA",
        "platform": "Glassdoor",
        "posted": "1 weeks ago",
        "experience": "5+ years",
        "saved": false,
        "logo": "TC",
        "description": "Exciting opportunity for a Digital Marketing Manager at TCS. Must have experience in SEO, SEM, Google Ads. Join our dynamic team in Mumbai.",
        "matchScore": 96,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Marketing"
    },
    {
        "id": 27,
        "title": "QA Automation Engineer",
        "company": "Reliance Industries",
        "location": "Mumbai, MH",
        "type": "Full-time",
        "salary": "\u20b910\u201315 LPA",
        "platform": "Naukri",
        "posted": "2 days ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "RI",
        "description": "Exciting opportunity for a QA Automation Engineer at Reliance Industries. Must have experience in Selenium, Cypress, Java. Join our dynamic team in Mumbai.",
        "matchScore": 89,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Tech"
    },
    {
        "id": 28,
        "title": "Senior Frontend Developer",
        "company": "Zomato",
        "location": "Gurgaon, HR",
        "type": "Remote",
        "salary": "\u20b926\u201341 LPA",
        "platform": "Instahyre",
        "posted": "1 weeks ago",
        "experience": "9+ years",
        "saved": true,
        "logo": "ZM",
        "description": "Exciting opportunity for a Senior Frontend Developer at Zomato. Must have experience in React, TypeScript, Next.js. Join our dynamic team in Gurgaon.",
        "matchScore": 74,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Tech"
    },
    {
        "id": 29,
        "title": "Growth Hacker",
        "company": "Wipro",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b913\u201320 LPA",
        "platform": "IIM Jobs",
        "posted": "7 days ago",
        "experience": "4+ years",
        "saved": false,
        "logo": "WI",
        "description": "Exciting opportunity for a Growth Hacker at Wipro. Must have experience in A/B Testing, User Acquisition. Join our dynamic team in Bangalore.",
        "matchScore": 84,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Marketing"
    },
    {
        "id": 30,
        "title": "Backend Engineer",
        "company": "Tech Mahindra",
        "location": "Pune, MH",
        "type": "Remote",
        "salary": "\u20b914\u201326 LPA",
        "platform": "Indeed",
        "posted": "4 weeks ago",
        "experience": "3+ years",
        "saved": true,
        "logo": "TM",
        "description": "Exciting opportunity for a Backend Engineer at Tech Mahindra. Must have experience in Go, Java, Spring Boot. Join our dynamic team in Pune.",
        "matchScore": 73,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Tech"
    },
    {
        "id": 31,
        "title": "Product Manager",
        "company": "Delhivery",
        "location": "Gurgaon, HR",
        "type": "Full-time",
        "salary": "\u20b927\u201339 LPA",
        "platform": "LinkedIn",
        "posted": "7 days ago",
        "experience": "7+ years",
        "saved": false,
        "logo": "DL",
        "description": "Exciting opportunity for a Product Manager at Delhivery. Must have experience in B2C, Agile, Roadmapping. Join our dynamic team in Gurgaon.",
        "matchScore": 86,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Tech"
    },
    {
        "id": 32,
        "title": "Wealth Manager",
        "company": "Ola",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b936\u201347 LPA",
        "platform": "Indeed",
        "posted": "2 weeks ago",
        "experience": "6+ years",
        "saved": true,
        "logo": "OL",
        "description": "Exciting opportunity for a Wealth Manager at Ola. Must have experience in Portfolio Management, CRM. Join our dynamic team in Bangalore.",
        "matchScore": 94,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Finance"
    },
    {
        "id": 33,
        "title": "Talent Acquisition Specialist",
        "company": "Ola",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b911\u201319 LPA",
        "platform": "IIM Jobs",
        "posted": "Just now",
        "experience": "4+ years",
        "saved": false,
        "logo": "OL",
        "description": "Exciting opportunity for a Talent Acquisition Specialist at Ola. Must have experience in Sourcing, Screening, LinkedIn. Join our dynamic team in Bangalore.",
        "matchScore": 65,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Operations"
    },
    {
        "id": 34,
        "title": "Project Manager",
        "company": "Ola",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b933\u201343 LPA",
        "platform": "Glassdoor",
        "posted": "3 weeks ago",
        "experience": "9+ years",
        "saved": false,
        "logo": "OL",
        "description": "Exciting opportunity for a Project Manager at Ola. Must have experience in PMP, Jira, Stakeholder Mgmt. Join our dynamic team in Bangalore.",
        "matchScore": 68,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Operations"
    },
    {
        "id": 35,
        "title": "Data Scientist",
        "company": "Infosys",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b914\u201322 LPA",
        "platform": "Indeed",
        "posted": "3 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "IN",
        "description": "Exciting opportunity for a Data Scientist at Infosys. Must have experience in Python, TensorFlow, PyTorch. Join our dynamic team in Bangalore.",
        "matchScore": 88,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Tech"
    },
    {
        "id": 36,
        "title": "Full Stack Developer",
        "company": "Razorpay",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b914\u201326 LPA",
        "platform": "Instahyre",
        "posted": "4 weeks ago",
        "experience": "4+ years",
        "saved": true,
        "logo": "RP",
        "description": "Exciting opportunity for a Full Stack Developer at Razorpay. Must have experience in MERN Stack, AWS. Join our dynamic team in Bangalore.",
        "matchScore": 61,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 37,
        "title": "Chartered Accountant",
        "company": "Flipkart",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b918\u201323 LPA",
        "platform": "Glassdoor",
        "posted": "4 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "FK",
        "description": "Exciting opportunity for a Chartered Accountant at Flipkart. Must have experience in Taxation, Auditing, GST. Join our dynamic team in Bangalore.",
        "matchScore": 85,
        "remote": false,
        "companySize": "Large",
        "industry": "Finance"
    },
    {
        "id": 38,
        "title": "Wealth Manager",
        "company": "Delhivery",
        "location": "Gurgaon, HR",
        "type": "Remote",
        "salary": "\u20b939\u201353 LPA",
        "platform": "Glassdoor",
        "posted": "4 weeks ago",
        "experience": "5+ years",
        "saved": false,
        "logo": "DL",
        "description": "Exciting opportunity for a Wealth Manager at Delhivery. Must have experience in Portfolio Management, CRM. Join our dynamic team in Gurgaon.",
        "matchScore": 63,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Finance"
    },
    {
        "id": 39,
        "title": "Content Strategist",
        "company": "Reliance Industries",
        "location": "Mumbai, MH",
        "type": "Full-time",
        "salary": "\u20b917\u201325 LPA",
        "platform": "LinkedIn",
        "posted": "2 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "RI",
        "description": "Exciting opportunity for a Content Strategist at Reliance Industries. Must have experience in Copywriting, SEO, Social Media. Join our dynamic team in Mumbai.",
        "matchScore": 97,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Marketing"
    },
    {
        "id": 40,
        "title": "iOS Developer",
        "company": "Flipkart",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b98\u201317 LPA",
        "platform": "Naukri",
        "posted": "2 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "FK",
        "description": "Exciting opportunity for a iOS Developer at Flipkart. Must have experience in Swift, SwiftUI. Join our dynamic team in Bangalore.",
        "matchScore": 77,
        "remote": true,
        "companySize": "Large",
        "industry": "Tech"
    },
    {
        "id": 41,
        "title": "Data Scientist",
        "company": "Lenskart",
        "location": "Delhi, DL",
        "type": "Remote",
        "salary": "\u20b913\u201324 LPA",
        "platform": "IIM Jobs",
        "posted": "3 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "LK",
        "description": "Exciting opportunity for a Data Scientist at Lenskart. Must have experience in Python, TensorFlow, PyTorch. Join our dynamic team in Delhi.",
        "matchScore": 96,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Tech"
    },
    {
        "id": 42,
        "title": "Investment Banker",
        "company": "Paytm",
        "location": "Noida, UP",
        "type": "Full-time",
        "salary": "\u20b910\u201319 LPA",
        "platform": "Naukri",
        "posted": "2 weeks ago",
        "experience": "3+ years",
        "saved": false,
        "logo": "PT",
        "description": "Exciting opportunity for a Investment Banker at Paytm. Must have experience in Valuation, M&A, Pitch Decks. Join our dynamic team in Noida.",
        "matchScore": 93,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Finance"
    },
    {
        "id": 43,
        "title": "HR Business Partner",
        "company": "PhonePe",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b913\u201322 LPA",
        "platform": "LinkedIn",
        "posted": "2 weeks ago",
        "experience": "2+ years",
        "saved": true,
        "logo": "PP",
        "description": "Exciting opportunity for a HR Business Partner at PhonePe. Must have experience in Employee Relations, Recruiting. Join our dynamic team in Bangalore.",
        "matchScore": 93,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Operations"
    },
    {
        "id": 44,
        "title": "Senior Frontend Developer",
        "company": "Meesho",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b926\u201341 LPA",
        "platform": "Indeed",
        "posted": "1 weeks ago",
        "experience": "6+ years",
        "saved": true,
        "logo": "MS",
        "description": "Exciting opportunity for a Senior Frontend Developer at Meesho. Must have experience in React, TypeScript, Next.js. Join our dynamic team in Bangalore.",
        "matchScore": 66,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 45,
        "title": "Data Scientist",
        "company": "Meesho",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b915\u201325 LPA",
        "platform": "IIM Jobs",
        "posted": "3 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "MS",
        "description": "Exciting opportunity for a Data Scientist at Meesho. Must have experience in Python, TensorFlow, PyTorch. Join our dynamic team in Bangalore.",
        "matchScore": 92,
        "remote": true,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 46,
        "title": "Full Stack Developer",
        "company": "Zerodha",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b916\u201323 LPA",
        "platform": "Glassdoor",
        "posted": "2 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "ZD",
        "description": "Exciting opportunity for a Full Stack Developer at Zerodha. Must have experience in MERN Stack, AWS. Join our dynamic team in Bangalore.",
        "matchScore": 94,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 47,
        "title": "Chartered Accountant",
        "company": "Infosys",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b913\u201321 LPA",
        "platform": "Naukri",
        "posted": "4 weeks ago",
        "experience": "1+ years",
        "saved": true,
        "logo": "IN",
        "description": "Exciting opportunity for a Chartered Accountant at Infosys. Must have experience in Taxation, Auditing, GST. Join our dynamic team in Bangalore.",
        "matchScore": 70,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Finance"
    },
    {
        "id": 48,
        "title": "Operations Manager",
        "company": "HDFC Bank",
        "location": "Mumbai, MH",
        "type": "Remote",
        "salary": "\u20b939\u201354 LPA",
        "platform": "Naukri",
        "posted": "1 weeks ago",
        "experience": "10+ years",
        "saved": false,
        "logo": "HB",
        "description": "Exciting opportunity for a Operations Manager at HDFC Bank. Must have experience in Supply Chain, Logistics, SAP. Join our dynamic team in Mumbai.",
        "matchScore": 63,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Operations"
    },
    {
        "id": 49,
        "title": "HR Business Partner",
        "company": "CRED",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b915\u201322 LPA",
        "platform": "Naukri",
        "posted": "3 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "CR",
        "description": "Exciting opportunity for a HR Business Partner at CRED. Must have experience in Employee Relations, Recruiting. Join our dynamic team in Bangalore.",
        "matchScore": 95,
        "remote": false,
        "companySize": "Startup",
        "industry": "Operations"
    },
    {
        "id": 50,
        "title": "Growth Hacker",
        "company": "Infosys",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b98\u201316 LPA",
        "platform": "LinkedIn",
        "posted": "5 days ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "IN",
        "description": "Exciting opportunity for a Growth Hacker at Infosys. Must have experience in A/B Testing, User Acquisition. Join our dynamic team in Bangalore.",
        "matchScore": 84,
        "remote": false,
        "companySize": "Enterprise",
        "industry": "Marketing"
    },
    {
        "id": 51,
        "title": "Full Stack Developer",
        "company": "ICICI Bank",
        "location": "Mumbai, MH",
        "type": "Full-time",
        "salary": "\u20b917\u201325 LPA",
        "platform": "LinkedIn",
        "posted": "3 weeks ago",
        "experience": "1+ years",
        "saved": false,
        "logo": "IB",
        "description": "Exciting opportunity for a Full Stack Developer at ICICI Bank. Must have experience in MERN Stack, AWS. Join our dynamic team in Mumbai.",
        "matchScore": 63,
        "remote": true,
        "companySize": "Enterprise",
        "industry": "Tech"
    },
    {
        "id": 52,
        "title": "Digital Marketing Manager",
        "company": "Freshworks",
        "location": "Chennai, TN",
        "type": "Contract",
        "salary": "\u20b934\u201352 LPA",
        "platform": "IIM Jobs",
        "posted": "4 weeks ago",
        "experience": "10+ years",
        "saved": false,
        "logo": "FW",
        "description": "Exciting opportunity for a Digital Marketing Manager at Freshworks. Must have experience in SEO, SEM, Google Ads. Join our dynamic team in Chennai.",
        "matchScore": 95,
        "remote": false,
        "companySize": "Large",
        "industry": "Marketing"
    },
    {
        "id": 53,
        "title": "Wealth Manager",
        "company": "Unacademy",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b933\u201344 LPA",
        "platform": "Glassdoor",
        "posted": "Just now",
        "experience": "9+ years",
        "saved": false,
        "logo": "UA",
        "description": "Exciting opportunity for a Wealth Manager at Unacademy. Must have experience in Portfolio Management, CRM. Join our dynamic team in Bangalore.",
        "matchScore": 79,
        "remote": false,
        "companySize": "Startup",
        "industry": "Finance"
    },
    {
        "id": 54,
        "title": "Android Developer",
        "company": "Zomato",
        "location": "Gurgaon, HR",
        "type": "Full-time",
        "salary": "\u20b918\u201330 LPA",
        "platform": "Indeed",
        "posted": "2 weeks ago",
        "experience": "1+ years",
        "saved": true,
        "logo": "ZM",
        "description": "Exciting opportunity for a Android Developer at Zomato. Must have experience in Kotlin, Jetpack Compose. Join our dynamic team in Gurgaon.",
        "matchScore": 84,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Tech"
    },
    {
        "id": 55,
        "title": "Social Media Lead",
        "company": "Delhivery",
        "location": "Gurgaon, HR",
        "type": "Full-time",
        "salary": "\u20b935\u201357 LPA",
        "platform": "LinkedIn",
        "posted": "3 weeks ago",
        "experience": "9+ years",
        "saved": false,
        "logo": "DL",
        "description": "Exciting opportunity for a Social Media Lead at Delhivery. Must have experience in Instagram, LinkedIn, Analytics. Join our dynamic team in Gurgaon.",
        "matchScore": 89,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Marketing"
    },
    {
        "id": 56,
        "title": "Digital Marketing Manager",
        "company": "Meesho",
        "location": "Bangalore, KA",
        "type": "Remote",
        "salary": "\u20b929\u201341 LPA",
        "platform": "Naukri",
        "posted": "3 weeks ago",
        "experience": "8+ years",
        "saved": true,
        "logo": "MS",
        "description": "Exciting opportunity for a Digital Marketing Manager at Meesho. Must have experience in SEO, SEM, Google Ads. Join our dynamic team in Bangalore.",
        "matchScore": 88,
        "remote": false,
        "companySize": "Startup",
        "industry": "Marketing"
    },
    {
        "id": 57,
        "title": "Financial Analyst",
        "company": "Zomato",
        "location": "Gurgaon, HR",
        "type": "Remote",
        "salary": "\u20b913\u201321 LPA",
        "platform": "Glassdoor",
        "posted": "1 weeks ago",
        "experience": "2+ years",
        "saved": false,
        "logo": "ZM",
        "description": "Exciting opportunity for a Financial Analyst at Zomato. Must have experience in Excel, Financial Modeling, SQL. Join our dynamic team in Gurgaon.",
        "matchScore": 88,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Finance"
    },
    {
        "id": 58,
        "title": "Operations Manager",
        "company": "PhonePe",
        "location": "Bangalore, KA",
        "type": "Full-time",
        "salary": "\u20b929\u201348 LPA",
        "platform": "Instahyre",
        "posted": "2 weeks ago",
        "experience": "10+ years",
        "saved": false,
        "logo": "PP",
        "description": "Exciting opportunity for a Operations Manager at PhonePe. Must have experience in Supply Chain, Logistics, SAP. Join our dynamic team in Bangalore.",
        "matchScore": 80,
        "remote": false,
        "companySize": "Mid-sized",
        "industry": "Operations"
    },
    {
        "id": 59,
        "title": "UI/UX Designer",
        "company": "Zerodha",
        "location": "Bangalore, KA",
        "type": "Contract",
        "salary": "\u20b910\u201316 LPA",
        "platform": "Indeed",
        "posted": "1 weeks ago",
        "experience": "3+ years",
        "saved": true,
        "logo": "ZD",
        "description": "Exciting opportunity for a UI/UX Designer at Zerodha. Must have experience in Figma, Adobe XD, Prototyping. Join our dynamic team in Bangalore.",
        "matchScore": 89,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    },
    {
        "id": 60,
        "title": "Senior Frontend Developer",
        "company": "Urban Company",
        "location": "Gurgaon, HR",
        "type": "Contract",
        "salary": "\u20b940\u201357 LPA",
        "platform": "Instahyre",
        "posted": "1 weeks ago",
        "experience": "10+ years",
        "saved": false,
        "logo": "UC",
        "description": "Exciting opportunity for a Senior Frontend Developer at Urban Company. Must have experience in React, TypeScript, Next.js. Join our dynamic team in Gurgaon.",
        "matchScore": 97,
        "remote": false,
        "companySize": "Startup",
        "industry": "Tech"
    }
];

const mockRecruiters = [
    { id: 1, name: 'Neha Kapoor', title: 'Senior Technical Recruiter', company: 'Razorpay', email: 'neha.k@razorpay.com', linkedin: 'linkedin.com/in/nehakapoor', phone: '+91-98765-43210', avatar: 'NK', status: 'Not Contacted', confidence: 94, jobId: 1 },
    { id: 2, name: 'Amit Desai', title: 'Talent Acquisition Lead', company: 'Zerodha', email: 'amit.d@zerodha.com', linkedin: 'linkedin.com/in/amitdesai', phone: '+91-98765-43211', avatar: 'AD', status: 'Replied', confidence: 88, jobId: 2 },
    { id: 3, name: 'Kavitha Menon', title: 'HR Recruiter', company: 'Flipkart', email: 'kavitha.m@flipkart.com', linkedin: 'linkedin.com/in/kavithamenon', phone: '+91-98765-43212', avatar: 'KM', status: 'Opened', confidence: 76, jobId: 3 },
    { id: 4, name: 'Rajesh Iyer', title: 'Engineering Recruiter', company: 'Freshworks', email: 'rajesh.i@freshworks.com', linkedin: 'linkedin.com/in/rajeshiyer', phone: '+91-98765-43213', avatar: 'RI', status: 'Not Contacted', confidence: 82, jobId: 1 },
    { id: 5, name: 'Priya Sharma', title: 'Technical Recruiter', company: 'PhonePe', email: 'priya.s@phonepe.com', linkedin: 'linkedin.com/in/priyasharma', phone: '+91-98765-43214', avatar: 'PS', status: 'Not Contacted', confidence: 91, jobId: 2 },
];

const mockMessages = [
    { id: 1, recruiterId: 1, recruiterName: 'Neha Kapoor', company: 'Razorpay', channel: 'Email', template: 'Brief Connection', subject: 'Excited about Sr. Frontend role at Razorpay', content: '', status: 'Replied', sentDate: 'Feb 14', responseTime: '18 hours', matchScore: 92 },
    { id: 2, recruiterId: 2, recruiterName: 'Amit Desai', company: 'Zerodha', channel: 'LinkedIn', template: 'Direct Ask', subject: 'React Developer Position', content: '', status: 'Opened', sentDate: 'Feb 15', responseTime: '—', matchScore: 87 },
    { id: 3, recruiterId: 3, recruiterName: 'Kavitha Menon', company: 'Flipkart', channel: 'Email', template: 'Cold Outreach', subject: 'Full Stack Engineer Opportunity', content: '', status: 'Sent', sentDate: 'Feb 16', responseTime: '—', matchScore: 78 },
    { id: 4, recruiterId: 4, recruiterName: 'Rajesh Iyer', company: 'Freshworks', channel: 'LinkedIn', template: 'Brief Connection', subject: 'Frontend Engineering Role', content: '', status: 'Replied', sentDate: 'Feb 17', responseTime: '8 hours', matchScore: 85 },
    { id: 5, recruiterId: 5, recruiterName: 'Priya Sharma', company: 'PhonePe', channel: 'Email', template: 'Direct Ask', subject: 'React Developer @ PhonePe', content: '', status: 'Sent', sentDate: 'Feb 18', responseTime: '—', matchScore: 91 },
    { id: 6, recruiterId: 1, recruiterName: 'Neha Kapoor', company: 'Razorpay', channel: 'LinkedIn', template: 'Follow-up', subject: 'Following up on Frontend role', content: '', status: 'Opened', sentDate: 'Feb 18', responseTime: '—', matchScore: 92 },
    { id: 7, recruiterId: 3, recruiterName: 'Kavitha Menon', company: 'Flipkart', channel: 'Email', template: 'Follow-up', subject: 'Follow-up: Full Stack Engineer', content: '', status: 'Replied', sentDate: 'Feb 19', responseTime: '4 hours', matchScore: 78 },
    { id: 8, recruiterId: 2, recruiterName: 'Amit Desai', company: 'Zerodha', channel: 'Email', template: 'Cold Outreach', subject: 'Re: React Developer Position', content: '', status: 'Sent', sentDate: 'Feb 19', responseTime: '—', matchScore: 87 },
];

const mockFollowUps = [
    { id: 1, recruiterId: 2, recruiterName: 'Amit Desai', company: 'Zerodha', dueDate: 'Today', daysOverdue: 0, channel: 'LinkedIn', originalDate: 'Feb 15', priority: 'high' },
    { id: 2, recruiterId: 5, recruiterName: 'Priya Sharma', company: 'PhonePe', dueDate: 'Tomorrow', daysOverdue: 0, channel: 'Email', originalDate: 'Feb 18', priority: 'medium' },
    { id: 3, recruiterId: 3, recruiterName: 'Kavitha Menon', company: 'Flipkart', dueDate: '2 days ago', daysOverdue: 2, channel: 'Email', originalDate: 'Feb 16', priority: 'high' },
];

const mockNotifications = [
    { id: 1, type: 'reply', title: 'Neha Kapoor replied!', body: 'Razorpay — She wants to schedule a call.', time: '2h ago', read: false, icon: '💬' },
    { id: 2, type: 'job', title: '12 new Frontend jobs', body: 'LinkedIn, Indeed matching your profile.', time: '4h ago', read: false, icon: '🔍' },
    { id: 3, type: 'followup', title: 'Follow-up due today', body: "Amit Desai @ Zerodha hasn't replied yet.", time: '6h ago', read: true, icon: '⏰' },
    { id: 4, type: 'reply', title: 'Rajesh Iyer replied!', body: 'Freshworks — Interested in your profile.', time: '1d ago', read: true, icon: '💬' },
];
const messageTemplates = [
    {
        id: 1,
        name: 'Brief Connection',
        channel: 'LinkedIn',
        score: 88,
        body: `Hi {recruiterName},\n\nI came across the {jobTitle} role at {company} and was genuinely excited — it aligns perfectly with my {experience} building high-impact products with {skills}.\n\nI'd love to connect and learn more about the team. Would you be open to a quick chat this week?\n\nBest,\n{myName}`,
    },
    {
        id: 2,
        name: 'Direct Ask',
        channel: 'Email',
        subject: 'Interested in {jobTitle} @ {company}',
        score: 82,
        body: `Hi {recruiterName},\n\nI'm reaching out about the {jobTitle} position at {company}. With {experience} of experience in {skills}, I believe I'd be a strong fit for this role.\n\nI'd welcome the chance to discuss how I can contribute to {company}'s mission. Are you available for a 15-minute call this week?\n\nBest regards,\n{myName}`,
    },
    {
        id: 3,
        name: 'Cold Outreach',
        channel: 'Email',
        subject: '{jobTitle} Role — Strong Match',
        score: 75,
        body: `Dear {recruiterName},\n\nI noticed your posting for {jobTitle} at {company} and wanted to express my strong interest. Over the past {experience}, I've developed expertise in {skills} and delivered measurable results at scale.\n\nI'd welcome the opportunity to discuss how I can bring value to {company}.\n\nThank you for your time,\n{myName}`,
    },
    {
        id: 4,
        name: 'Follow-up',
        channel: 'Email',
        subject: 'Following up — {jobTitle} at {company}',
        score: 79,
        body: `Hi {recruiterName},\n\nI wanted to follow up on my earlier message about the {jobTitle} position at {company}. I remain very excited about this opportunity and wanted to confirm my continued interest.\n\nPlease let me know if you need any additional information from me.\n\nBest,\n{myName}`,
    },
    {
        id: 5,
        name: 'Video Intro',
        channel: 'Video',
        score: 91,
        body: `Hi {recruiterName},\n\nI've recorded a 60-second intro about why I'm excited about {company} and the {jobTitle} role — [Video Link]. I'd love to connect if this resonates!\n\n{myName}`,
    },
];

const analyticsData = [
    { week: 'Jan W1', sent: 4, opened: 3, replied: 1 },
    { week: 'Jan W2', sent: 7, opened: 5, replied: 2 },
    { week: 'Jan W3', sent: 5, opened: 4, replied: 2 },
    { week: 'Jan W4', sent: 9, opened: 6, replied: 3 },
    { week: 'Feb W1', sent: 11, opened: 8, replied: 4 },
    { week: 'Feb W2', sent: 8, opened: 7, replied: 3 },
    { week: 'Feb W3', sent: 14, opened: 10, replied: 5 },
    { week: 'Feb W4', sent: 12, opened: 9, replied: 4 },
];

export function AppProvider({ children }) {
    const [isAuthenticated, setIsAuthenticated] = useState(false);
    const [user, setUser] = useState({
        name: 'Arjun Mehta',
        email: 'arjun@example.in',
        phone: '',
        location: 'Bangalore, KA',
        headline: 'Senior Frontend Developer',
        skills: 'React, TypeScript, Node.js, AWS',
        avatar: 'AM',
        plan: 'Accelerate',
        weeklyGoal: 10,
        integrations: { linkedin: false, gmail: false, outlook: false, instahyre: false },
    });
    const [jobs, setJobs] = useState(mockJobs);
    const [recruiters, setRecruiters] = useState(mockRecruiters);
    const [messages, setMessages] = useState(mockMessages);
    const [followUps, setFollowUps] = useState(mockFollowUps);
    const [notifications, setNotifications] = useState(mockNotifications);
    const [searchResults, setSearchResults] = useState([]);
    const [loading, setLoading] = useState(false);
    const [darkMode, setDarkMode] = useState(true);

    const login = (phone) => {
        setUser(prev => ({ ...prev, phone }));
        setIsAuthenticated(true);
    };
    const logout = () => setIsAuthenticated(false);

    const savedJobs = jobs.filter(j => j.saved);

    const toggleSaveJob = (id) =>
        setJobs(prev => prev.map(j => j.id === id ? { ...j, saved: !j.saved } : j));

    const saveJob = (job) =>
        setJobs(prev => prev.some(j => j.id === job.id) ? prev : [...prev, { ...job, saved: true }]);

    const addRecruiter = (r) =>
        setRecruiters(prev => prev.some(x => x.id === r.id) ? prev : [r, ...prev]);

    const updateRecruiterStatus = (id, status) =>
        setRecruiters(prev => prev.map(r => r.id === id ? { ...r, status } : r));

    const sendMessage = (msg) => {
        const newMsg = { id: Date.now(), ...msg, sentDate: 'Today', responseTime: '—', status: 'Sent' };
        setMessages(prev => [newMsg, ...prev]);
    };

    const updateUser = (data) => setUser(prev => ({ ...prev, ...data }));

    const toggleIntegration = (key) =>
        setUser(prev => ({ ...prev, integrations: { ...prev.integrations, [key]: !prev.integrations[key] } }));

    const markNotifRead = (id) =>
        setNotifications(prev => prev.map(n => n.id === id ? { ...n, read: true } : n));

    const markAllNotifsRead = () =>
        setNotifications(prev => prev.map(n => ({ ...n, read: true })));

    const dismissFollowUp = (id) =>
        setFollowUps(prev => prev.filter(f => f.id !== id));

    const unreadCount = notifications.filter(n => !n.read).length;

    const stats = {
        savedJobs: savedJobs.length,
        recruiters: recruiters.length,
        messagesSent: messages.length,
        responseRate: messages.length ? Math.round((messages.filter(m => m.status === 'Replied').length / messages.length) * 100) : 0,
        funnel: {
            jobSearch: jobs.length,
            enrichment: recruiters.length,
            outreach: messages.length,
            responses: messages.filter(m => m.status === 'Replied').length,
        },
        weeklyProgress: 7,
        aiScore: 78,
    };

    return (
        <AppContext.Provider value={{
            isAuthenticated, login, logout,
            user, updateUser, toggleIntegration,
            jobs, savedJobs, toggleSaveJob, saveJob, searchResults, setSearchResults,
            recruiters, addRecruiter, updateRecruiterStatus,
            messages, sendMessage,
            followUps, dismissFollowUp,
            notifications, unreadCount, markNotifRead, markAllNotifsRead,
            messageTemplates,
            analyticsData,
            stats,
            loading, setLoading,
            darkMode, setDarkMode,
        }}>
            {children}
        </AppContext.Provider>
    );
}

export function useApp() {
    const ctx = useContext(AppContext);
    if (!ctx) throw new Error('useApp must be used within AppProvider');
    return ctx;
}
